### ISSUE TITLE
Doubts during use

### ISSUE THREAD

**Issue by LDAIprotein** [anton-bushuiev/PPIRef#4]
Hello, this is a very good work, but I found a problem that bothered me during use. I used a protein 7qih_A_B (CASP15 name: H1106) to search for similar PPIs and found that only 1xxh_A_B (IDist = 0.0303 IS-score = 0.146) was searched. Further, I used two prediction models of 7qih (completely different docking modes, one of which was a high-scoring prediction model TM: 0.933 and the other was a low-scoring prediction model TM: 0.194) to search for similar PPIs, but got the same result. This is a very strange phenomenon.
High quality model:
![1717134018717](https://github.com/anton-bushuiev/PPIRef/assets/104683463/71c1cb8c-357e-4766-90ee-17bebf3e25c5)
PPI search results：
![image](https://github.com/anton-bushuiev/PPIRef/assets/104683463/10a1e418-fd8a-4ce9-aa70-c23da2a9ed51)

Low quality model:
![image](https://github.com/anton-bushuiev/PPIRef/assets/104683463/8cacc418-664f-49a2-94ed-f790b6a22d0a)
PPI search results：
![image](https://github.com/anton-bushuiev/PPIRef/assets/104683463/9dc32397-f90d-493f-ba40-3aaf927773de)

**Comment by LDAIprotein** [comment]
Does this mean that the PPI pattern of the query is highly correlated with its sequence?

**Comment by anton-bushuiev** [comment]
Hi @LDAIprotein ,

This is extremely unlikely to get nearly the same results for so different interactions. My guess would be that this is caused by some bug leading to the same PPI interface being actually used for the search (and slightly different distances for some of the found entries could be probably caused by numerical issues). 

If you share the script you are using, I can take a look.

**Comment by LDAIprotein** [comment]
Thank you for giving us feedback in time. We know the reason: the input PDB structure is full-length (not CutOff 6A), which leads to the exact same search results. This is a wrong way. But through this way, we also understand that the search method of IDist seems to have some correlation with the sequence.

**Comment by anton-bushuiev** [comment]
I see. It makes good sense! Please let me know if there is anything else unclear.

**Comment by LDAIprotein** [comment]
Thank you. I have no other questions. We believe that your work will have a positive impact on this field. This is a very good work. We look forward to your 10A data and a series of extended research.

**Comment by anton-bushuiev** [comment]
Hi @LDAIprotein! The 10A data are now available. There are two version: all 10A PPI interfaces extracted from PDB and all 10A PPI interfaces extracted from PDB-REDO. Please let me know if you use it and have any issues.

**Comment by LDAIprotein** [comment]
Thanks for the reminder! We will use it. @anton-bushuiev
